### ISSUE TITLE
didn‘t work on dero.

### ISSUE THREAD

**Issue by SKlayer** [SadBatman/cryptonote-dero-pool#4]
2018-03-23 10:08:44 [master] API died, spawning replacement...

/coin/dero/derpol/cryptonote-dero-pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/coin/dero/derpol/cryptonote-dero-pool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

2018-03-23 10:08:46 [master] Payment processor died, spawning replacement...
2018-03-23 10:08:47 [charts] Started

/coin/dero/derpol/cryptonote-dero-pool/node_modules/mailgun.js/lib/client.js:18
class Client {
^^^^^

SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/coin/dero/derpol/cryptonote-dero-pool/node_modules/mailgun.js/index.js:5:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

2018-03-23 10:08:47 [master] API died, spawning replacement...

it works on my 0.99 pool,but...

**Comment by SKlayer** [comment]
using 
nvm use 0.4.8
solved
